heat_template_version: 2021-04-16

description: Template para criação de instâncias para alunos em sala de aula.

parameters:
  student_count:
    type: number
    description: Número de alunos (instâncias a serem criadas)
    default: 10
  image_id:
    type: string
    description: ID da imagem com ambiente pré-configurado
  flavor:
    type: string
    description: Tipo de instância (flavor)
    default: m1.small
  network_id:
    type: string
    description: ID da rede para as instâncias

resources:
  student_instances:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: student_count }
      resource_def:
        type: OS::Nova::Server
        properties:
          name: 
            str_replace:
              template: "aluno-INSTANCE"
              params: 
                INSTANCE: "%index%"
          image: { get_param: image_id }
          flavor: { get_param: flavor }
          networks:
            - network: { get_param: network_id }

outputs:
  instances_info:
    description: Informações das instâncias criadas
    value: { get_attr: [student_instances, show] }
